let locations = [
	{
		name: "Rothberg's Roasters ||",
		desc: 'Breakfast, lunch, dinner, pizza, sandwiches, soups, fruit, dessert, coffee',
		hours: '8:00 AM - 8:00 PM',
		location: 'Scott Hall',
		open: true,
		image: false,
		oncampus: true,
	},
	{
		name: "Tazzo D'Oro",
		desc: "Coffee, espresso, tea, panini, desserts, pastries",
		hours: "7:00 AM - 7:00 PM",
		location: 'Gates & Hillman Centers' ,
		open: true,
		image: false,
		oncampus: true,
	},
	{
		name: 'Heinz Café',
		desc: "Grab-and-go items, bagels, hummus, baked goods, granola, and yogurt",
		hours: "8:30 AM - 6:00 PM",
		location: 'Hamburg Hall (Heinz)',
		open: true,
		image: false,
		oncampus: true,
	},
	{
		name: "iNoodle",
		desc: "Asian cuisine, rice/noodle bowls, hot/cold boba tea",
		hours: "8:00 AM - 7:30 PM",
		location: 'Newell-Simon Hall',
		open: true,
		image: false,
		oncampus: true,
	},
	{
		name: "La Prima Espresso",
		desc: "Free trade and organic espresso, cappuccino, coffee, pastries, soup, sandwiches",
		hours: "8:00 AM - 6:00 PM",
		location: 'Wean Hall',
		open: false,
		image: false,
		oncampus: true,
	},
	{
		name: "Gingers Express",
		desc: "Deli sandwiches, salads, soups, hot entrées, coffee, organic teas, bottled juices, baked goods",
		hours: "8:00 AM - 4:00 PM",
		location: 'Baker Hall',
		open: false,
		image: false,
		oncampus: true,
	},
	{
		name: "Maggie Murph Café",
		desc: "Starbucks, Tazo tea, pastries, bagels, sandwiches, soup, salad, sushi, breakfast",
		hours: "Open 24 Hours",
		location: 'Hunt Library',
		open: false,
		image: false,
		oncampus: true,
	},
	{
		name: "The Zebra Lounge",
		desc: "Free trade organic tea and coffee, sandwiches, soup, pastries",
		hours: "8:00 AM - 5:00 PM",
		location: 'College of Fine Arts',
		open: false,
		image: false,
		oncampus: true,
	},
	{
		name: "The Exchange",
		desc: "Sandwiches, salad, soup, hot entrées, coffee, tea, baked goods, fruit, yogurt",
		hours: "8:00 AM - 8:00 PM",
		location: 'Posner Hall (Tepper)',
		open: false,
		image: false,
		oncampus: true,
	},
	{
		name: "Subway",
		desc: "Sandwiches",
		hours: "8:00 AM - 11:00 PM",
		location: 'Craig Street',
		open: true,
		image: false,
		oncampus: false,
	},
];

// let locations = [
// 	{
// 		name: 'C The Underground',
// 		desc: 'Hamburgers, chicken tenders, pasta, soup, salad, breakfast, fruit, dessert',
// 		hours: '8:30 AM - 2:00 AM',
// 		location: 'Morewood Gardens, Lower',
// 		order: false,
// 		image: false,
// 	},
// 	{
// 		name: 'B The Underground',
// 		desc: 'Hamburgers, chicken tenders, pasta, soup, salad, breakfast, fruit, dessert',
// 		hours: '8:30 AM - 2:00 AM',
// 		location: 'Morewood Gardens, Lower',
// 		order: true,
// 		image: false,
// 	},
// 	{
// 		name: 'A The Underground',
// 		desc: 'Hamburgers, chicken tenders, pasta, soup, salad, breakfast, fruit, dessert',
// 		hours: '8:30 AM - 2:00 AM',
// 		location: 'Morewood Gardens, Lower',
// 		order: true,
// 		image: false,
// 	}
// ];
