let locations = [
	{
		name: "Rothberg's Roasters ||",
		desc: 'Breakfast, lunch, dinner, pizza, sandwiches, soups, fruit, dessert, coffee',
		hours: '8:00 AM - 8:00 PM',
		location: 'Scott Hall',
		order: true,
		image: false,
	},
	{
		name: "Tazzo D'Oro",
		desc: "Coffee, espresso, tea, panini, desserts, pastries",
		hours: "7:00 AM - 7:00 PM",
		location: 'Gates & Hillman Centers' ,
		order: true,
		image: false,
	},
	{
		name: 'Heinz Café',
		desc: "Grab-and-go items, bagels, hummus, baked goods, granola, and yogurt",
		hours: "8:30 AM - 6:00 PM",
		location: 'Hamburg Hall (Heinz)',
		order: true,
		image: false,
	},
	{
		name: "iNoodle",
		desc: "Asian cuisine, rice/noodle bowls, hot/cold boba tea",
		hours: "8:00 AM - 7:30 PM",
		location: 'Newell-Simon Hall',
		order: true,
		image: false,
	},
	{
		name: "La Prima Espresso",
		desc: "Free trade and organic espresso, cappuccino, coffee, pastries, soup, sandwiches",
		hours: "8:00 AM - 6:00 PM",
		location: 'Wean Hall',
		order: true,
		image: false,
	},
	{
		name: "Gingers Express",
		desc: "Deli sandwiches, salads, soups, hot entrées, coffee, organic teas, bottled juices, baked goods",
		hours: "8:00 AM - 4:00 PM",
		location: 'Baker Hall',
		order: true,
		image: false,
	},
	{
		name: "Maggie Murph Café",
		desc: "Starbucks, Tazo tea, pastries, bagels, sandwiches, soup, salad, sushi, breakfast",
		hours: "Open 24 Hours",
		location: 'Hunt Library',
		order: true,
		image: false,
	},
	{
		name: "The Zebra Lounge",
		desc: "Free trade organic tea and coffee, sandwiches, soup, pastries",
		hours: "8:00 AM - 5:00 PM",
		location: 'College of Fine Arts',
		order: true,
		image: false,
	},
	{
		name: "The Exchange",
		desc: "Sandwiches, salad, soup, hot entrées, coffee, tea, baked goods, fruit, yogurt",
		hours: "8:00 AM - 8:00 PM",
		location: 'Posner Hall (Tepper)',
		order: false,
		image: false,
	}
];
